name: Container image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

env:
  TEST_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
  RELEASE_TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

jobs:
  build:
    name: Build, test and release image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          file: ./alpine-builder.Containerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=image
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Verify image's target platforms
        run: |
          amd64_uname="$(docker run --rm --platform linux/amd64 ${{ env.TEST_TAG }} /bin/bash -c 'uname -m')"
          arm64_uname="$(docker run --rm --platform linux/arm64 ${{ env.TEST_TAG }} /bin/bash -c 'uname -m')"
          rc=0
          if [ "$amd64_uname" != x86_64 ]; then
            echo "Wrong machine hardware name for amd64 image: got $amd64_uname, expected x86_64" >&2
            rc=1
          fi
          if [ "$arm64_uname" != aarch64 ]; then
            echo "Wrong machine hardware name for arm64 image: got $arm64_uname, expected aarch64" >&2
            rc=1
          fi
          if [ $rc -ne 0 ]; then
            exit 1
          fi
      - name: Test cc-rules plugin
        run: |
          for platform in linux/amd64 linux/arm64; do
            echo "*** Testing $platform image"
            docker run --rm --platform "$platform" ${{ env.TEST_TAG }} /bin/bash -c "git clone https://github.com/please-build/cc-rules && cd cc-rules && ./pleasew test -v notice"
          done
      - name: Test python-rules plugin
        run: |
          for platform in linux/amd64 linux/arm64; do
            echo "*** Testing $platform image"
            docker run --rm --platform "$platform" ${{ env.TEST_TAG }} /bin/bash -c "git clone https://github.com/please-build/python-rules && cd python-rules && ./pleasew test -v notice"
          done
      - name: Authenticate to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: the-hogfather
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          file: ./alpine-builder.Containerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=image
          push: true
          tags: ${{ env.RELEASE_TAG }}
